AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups for EC2 Instances

Parameters:
  VPCId:
    Type: String
  PublicEC2Id:
    Type: String
  PrivateEC2Id:
    Type: String

Resources:
  PublicEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for public EC2 instance
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Replace with your specific IP for better security

  PrivateEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for private EC2 instance
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref PublicEC2SecurityGroup

  PublicEC2SecurityGroupAssociation:
    Type: AWS::EC2::SecurityGroupAssociation
    Properties:
      InstanceId: !Ref PublicEC2Id
      SecurityGroupId: !Ref PublicEC2SecurityGroup

  PrivateEC2SecurityGroupAssociation:
    Type: AWS::EC2::SecurityGroupAssociation
    Properties:
      InstanceId: !Ref PrivateEC2Id
      SecurityGroupId: !Ref PrivateEC2SecurityGroup

Outputs:
  PublicEC2SecurityGroupId:
    Description: Public EC2 Security Group ID
    Value: !Ref PublicEC2SecurityGroup
  PrivateEC2SecurityGroupId:
    Description: Private EC2 Security Group ID
    Value: !Ref PrivateEC2SecurityGroup